# Generated by Django 2.0 on 2018-05-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exambattle', '0002_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
