# Generated by Django 2.0 on 2018-05-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exambattle', '0005_auto_20180528_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ans1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='ans2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='ans3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='ans4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
